TOP = .
include $(TOP)/configure/CONFIG

DIRS += configure
DIRS += attocubeIOCApp/Db
DIRS += attocubeIOCApp/src
DIRS += iocBoot/iocexample
DIRS += attocubeIOCApp/opi/edl

include $(TOP)/configure/RULES_TOP

uninstall:
	rm -rf ./bin
